server:
    port: 8080
    mode: debug
storage:
    type: local
    local_path: ./data
    s3:
        endpoint: ""
        access_key: ""
        secret_key: ""
        bucket: ""
database:
    type: sqlite
    dsn: cloud-for-save.db
